version: '3'
networks:
    proxy:
        external:
            name: traefik_proxy
    backend:
        driver: bridge
        internal: true
    database:
        external:
            name: mysql8_backend
services:
    web:
        image: ezitisitis/laravel
        container_name: playme3_web
        command: /bin/bash -c "php-fpm8.1 -F"
        restart: always
        volumes:
            - .:/app
        labels:
            traefik.enable: "false"
        networks:
            - proxy
            - backend
            - database
    nginx:
        image: nginx:latest
        container_name: playme3_nginx
        restart: always
        volumes:
            - ./public:/app/public
            - ./storage/app:/app/storage/app
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./docker/nginx-logs:/var/log/nginx
        depends_on:
            - web
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=traefik_proxy"
            - "traefik.http.routers.playme3.entrypoints=http"
            - "traefik.http.routers.playme3.rule=Host(`playme3.localhost`,`www.playme3.localhost`)"
            - "traefik.http.routers.playme3.middlewares=traefik-https-redirect"
            - "traefik.http.routers.playme3-secure.entrypoints=https"
            - "traefik.http.routers.playme3-secure.rule=Host(`playme3.localhost`,`www.playme3.localhost`)"
            - "traefik.http.routers.playme3-secure.tls.certresolver=http"
        networks:
            - proxy
            - backend